### ISSUE TITLE
Download datasets and models via the given link does not work

### ISSUE THREAD

**Issue by ramsey-coding** [iCSawyer/CodeSuggestion#1]
I am from United States and have been trying to download dataset from the given link i.e. Baidu link.

https://pan.baidu.com/s/1evYOESMCyZUozDm775ebuw?pwd=152u#list/path=%2F

I have spent a lot of time to download it with no luck. 

Can you please share the dataset at the least using google drive or some other way so that others can download.

Looking forward to your prompt response.

**Comment by iCSawyer** [comment]
I have uploaded datasets via Google drive.

**Comment by ramsey-coding** [comment]
Thanks a lot @iCSawyer
