### ISSUE TITLE
Can you provide more detailed usage steps?

### ISSUE THREAD

**Issue by Addlien** [iCSawyer/CodeSuggestion#10]
Can you provide more detailed usage steps?
How can I combine the search part with other models if I want to use it?

Thank you for your inspiring work.

**Comment by Addlien** [comment]
additionally，where is the code for retriever？

**Comment by iCSawyer** [comment]
Thank you for your following. For general DL models, you can simply concatenate the search exemplar with the context to be complete (e.g., the string is {exemplar}{special symbol for concatenation}{context}); for LLMs, you can fill the exemplars into the positions of the templates (shown in our paper and code). 

We utilize the retriever code of [ReACC](https://github.com/microsoft/ReACC) and [PyLucene](https://lucene.apache.org/pylucene/). Notice that any appropriate search tool you prefer is okay for the retrieval.
