### ISSUE TITLE
problem with lucene

### ISSUE THREAD

**Issue by ShuyinOuyang** [iCSawyer/CodeSuggestion#12]
Thanks for providing the code for this wonderful work!
I am currently working on a code search with Lucene.
In the paper, the author mentioned using Lucene for information retrieval, can you provide the script for that part?

**Comment by iCSawyer** [comment]
Thank you for your following!

In our work, we use [PyLucene](https://lucene.apache.org/pylucene/) to perform IR based search. Specifically, we just made (very minor) modifications on `IndexFiles.py` and `SearchFiles.py` of the [examples](https://svn.apache.org/viewvc/lucene/pylucene/trunk/samples/).
