### ISSUE TITLE
Download models via the given link does not work

### ISSUE THREAD

**Issue by ramsey-coding** [iCSawyer/CodeSuggestion#2]
I am from United States and have been trying to download dataset from the given link i.e. Baidu link.

https://pan.baidu.com/s/1evYOESMCyZUozDm775ebuw?pwd=152u#list/path=%2F

I have spent a lot of time to download it with no luck. Furthermore, it needs to create an account with a phone number from inside China.

Can you please upload the model in Zenodo so that others can download as well.

Looking forward to your prompt response.

**Comment by iCSawyer** [comment]
I have tried uploading models to many platforms such as Zenodo, Figshare, Google Drive, and Dropbox, but failed because of the storage space limit. If you need a specific model, you can email me.
