### ISSUE TITLE
how would I run the experiments for RQ2?

### ISSUE THREAD

**Issue by ramsey-coding** [iCSawyer/CodeSuggestion#3]
Could you provide guidance on running experiments for RQ2? The steps seem to be missing.

**Comment by ramsey-coding** [comment]
For example, from where to find this json file? I can't find this file in the shared dataset.

```
    search_results_path = f"datasets/search_results/{conf.search_tool}/test_bpe_java.json"
```

**Comment by ramsey-coding** [comment]
how to generate the `test_bpe_java.json` file? We can't find this file anywhere in the artifact.

**Comment by iCSawyer** [comment]
Hi! I missed it when I uploaded the datasets, and I will update it soon.
