### ISSUE TITLE
Inquiry on NL2NL Example and Dataset Construction Details

### ISSUE THREAD

**Issue by ramsey-coding** [iCSawyer/CodeSuggestion#5]
I understand NL2NL uses natural language descriptions in both source and target as the key information to search. However, there is no mention how this dataset was constructed. Can you provide details?

**Comment by ramsey-coding** [comment]
@iCSawyer any update?

**Comment by iCSawyer** [comment]
NL2NL is not a dataset but one of code retrieval strategies. We apply it to different retrievers and construct the results.
