### ISSUE TITLE
Pytorrent dataset

### ISSUE THREAD

**Issue by ramsey-coding** [iCSawyer/CodeSuggestion#8]
Pytorrent artifact shows the following:

- https://zenodo.org/records/4546290

PyTorrent_Both_Docstrings_UserComments.zip
PyTorrent_Both_Docstrings_UserComments_v2.zip
PyTorrent_Docstrings.zip
PyTorrent_Docstrings_v2.zip
PyTorrent_UserComments.zip
PyTorrent_UserComments_v2.zip

Which file have you used in your paper?

**Comment by ramsey-coding** [comment]
@iCSawyer Any update?

**Comment by iCSawyer** [comment]
Hi! [PyTorrent_Both_Docstrings_UserComments_v2.zip](https://zenodo.org/records/4546290/files/PyTorrent_Both_Docstrings_UserComments_v2.zip?download=1) is PyTorrent dataset we refer to.
