### ISSUE TITLE
Confused regarding Figure 1 

### ISSUE THREAD

**Issue by ramsey-coding** [iCSawyer/CodeSuggestion#9]
In Figure 1 it is shown that:

```
def get_data_from_database( conn, idx, field): 
        cursor = ?
```

However, from code it feels that for NL2NL during prompting you prompt the model with:

```
get data from database <- comment
Example1     <- An example after searching similar code
```

So you don't actually prompt like the following:
```
def get_data_from_database( conn, idx, field): 
        cursor = ?
```

Is this understanding correct?

**Comment by ramsey-coding** [comment]
@iCSawyer Any update?

**Comment by iCSawyer** [comment]
Hi! For three RQs, we use the generator to perform code-to-code suggestions, and NL is only used for code retrieval.
